
export default {
  formId: "filterForm",
  formField: {
    keyword: {
      name: "keyword",
      label: "keyword",
      requiredErrorMsg: "keyword field is required",
    },
    attractionId: {
      name: "attractionId",
      label: "Attraction ID",
      requiredErrorMsg: "Attraction ID field is required",
    },
    venueId: {
      name: "venueId",
      label: "Venue ID",
      requiredErrorMsg: "Venue ID field is required",
    },
    postalCode: {
      name: "postalCode",
      label: "Postal Code",
      requiredErrorMsg: "Postal Code field is required",
    },
    latlong: {
      name: "latlong",
      label: "Latitude and Longitude",
      requiredErrorMsg: "Latitude and Longitude field is required (deprecated)",
    },
    radius: {
      name: "radius",
      label: "Radius",
      requiredErrorMsg: "Radius field is required",
    },
    unit: {
      name: "unit",
      label: "Unit of Radius",
      requiredErrorMsg: "Unit of Radius field is required",
      options: ["miles", "km"],
      defaultValue: "miles",
    },
    source: {
      name: "source",
      label: "Source",
      requiredErrorMsg: "Source field is required",
      options: ["ticketmaster", "universe", "frontgate", "tmr"],
    },
    locale: {
      name: "locale",
      label: "Locale",
      requiredErrorMsg: "Locale field is required",
    },
    marketId: {
      name: "marketId",
      label: "Market ID",
      requiredErrorMsg: "Market ID field is required",
    },
    startDateTime: {
      name: "startDateTime",
      label: "Start Date Time",
      requiredErrorMsg: "Start Date Time field is required",
    },
    endDateTime: {
      name: "endDateTime",
      label: "End Date Time",
      requiredErrorMsg: "End Date Time field is required",
    },
    includeTBA: {
      name: "includeTBA",
      label: "Include TBA",
      requiredErrorMsg: "Include TBA field is required",
      options: ["yes", "no", "only"],
    },
    includeTBD: {
      name: "includeTBD",
      label: "Include TBD",
      requiredErrorMsg: "Include TBD field is required",
      options: ["yes", "no", "only"],
    },
    includeTest: {
      name: "includeTest",
      label: "Include Test",
      requiredErrorMsg: "Include Test field is required",
      options: ["yes", "no", "only"],
    },
    size: {
      name: "size",
      label: "Page Size",
      requiredErrorMsg: "Page Size field is required",
    },
    page: {
      name: "page",
      label: "Page Number",
      requiredErrorMsg: "Page Number field is required",
    },
    sort: {
      name: "sort",
      label: "Sorting Order",
      requiredErrorMsg: "Sorting Order field is required",
      options: [
        "name,asc",
        "name,desc",
        "date,asc",
        "date,desc",
        "relevance,asc",
        "relevance,desc",
        "distance,asc",
        "name,date,asc",
        "name,date,desc",
        "date,name,asc",
        "date,name,desc",
        "distance,date,asc",
        "onSaleStartDate,asc",
        "id,asc",
        "venueName,asc",
        "venueName,desc",
        "random",
      ],
      defaultValue: "relevance,desc",
    },
    onsaleStartDateTime: {
      name: "onsaleStartDateTime",
      label: "Onsale Start Date Time",
      requiredErrorMsg: "Onsale Start Date Time field is required",
    },
    onsaleEndDateTime: {
      name: "onsaleEndDateTime",
      label: "Onsale End Date Time",
      requiredErrorMsg: "Onsale End Date Time field is required",
    },
    city: {
      name: "city",
      label: "City",
      requiredErrorMsg: "City field is required",
    },
    countryCode: {
      name: "countryCode",
      label: "Country Code",
      requiredErrorMsg: "Country Code field is required",
    },
    stateCode: {
      name: "stateCode",
      label: "State Code",
      requiredErrorMsg: "State Code field is required",
    },
    classificationName: {
      name: "classificationName",
      label: "Classification Name",
      requiredErrorMsg: "Classification Name field is required",
    },
    classificationId: {
      name: "classificationId",
      label: "Classification ID",
      requiredErrorMsg: "Classification ID field is required",
    },
    dmaId: {
      name: "dmaId",
      label: "DMA ID",
      requiredErrorMsg: "DMA ID field is required",
    },
    localStartDateTime: {
      name: "localStartDateTime",
      label: "Local Start Date Time",
      requiredErrorMsg: "Local Start Date Time field is required",
    },

    localStartEndDateTime: {
      name: "localStartEndDateTime",
      label: "Local Start-End Date Time",
      requiredErrorMsg: "Local Start-End Date Time field is required",
    },
    startEndDateTime: {
      name: "startEndDateTime",
      label: "Start-End Date Time",
      requiredErrorMsg: "Start-End Date Time field is required",
    },
    publicVisibilityStartDateTime: {
      name: "publicVisibilityStartDateTime",
      label: "Public Visibility Start Date Time",
      requiredErrorMsg: "Public Visibility Start Date Time field is required",
    },
    preSaleDateTime: {
      name: "preSaleDateTime",
      label: "Pre-sale Date Time",
      requiredErrorMsg: "Pre-sale Date Time field is required",
    },
    onsaleOnStartDate: {
      name: "onsaleOnStartDate",
      label: "Onsale On Start Date",
      requiredErrorMsg: "Onsale On Start Date field is required",
    },
    onsaleOnAfterStartDate: {
      name: "onsaleOnAfterStartDate",
      label: "Onsale On After Start Date",
      requiredErrorMsg: "Onsale On After Start Date field is required",
    },
    collectionId: {
      name: "collectionId",
      label: "Collection ID",
      requiredErrorMsg: "Collection ID field is required",
    },
    segmentId: {
      name: "segmentId",
      label: "Segment ID",
      requiredErrorMsg: "Segment ID field is required",
    },
    segmentName: {
      name: "segmentName",
      label: "Segment Name",
      requiredErrorMsg: "Segment Name field is required",
    },
    includeFamily: {
      name: "includeFamily",
      label: "Include Family",
      requiredErrorMsg: "Include Family field is required",
      options: ["yes", "no", "only"],
      defaultValue: "yes",
    },
    promoterId: {
      name: "promoterId",
      label: "Promoter ID",
      requiredErrorMsg: "Promoter ID field is required",
    },
    genreId: {
      name: "genreId",
      label: "Genre ID",
      requiredErrorMsg: "Genre ID field is required",
    },
    subGenreId: {
      name: "subGenreId",
      label: "SubGenre ID",
      requiredErrorMsg: "SubGenre ID field is required",
    },
    typeId: {
      name: "typeId",
      label: "Type ID",
      requiredErrorMsg: "Type ID field is required",
    },
    subTypeId: {
      name: "subTypeId",
      label: "SubType ID",
      requiredErrorMsg: "SubType ID field is required",
    },
    geoPoint: {
      name: "geoPoint",
      label: "GeoPoint",
      requiredErrorMsg: "GeoPoint field is required",
    },
    preferredCountry: {
      name: "preferredCountry",
      label: "Preferred Country",
      requiredErrorMsg: "Preferred Country field is required",
      options: ["us", "ca"],
      defaultValue: "us",
    },
    includeSpellcheck: {
      name: "includeSpellcheck",
      label: "Include Spellcheck",
      requiredErrorMsg: "Include Spellcheck field is required",
      options: ["yes", "no"],
      defaultValue: "no",
    },
    domain: {
      name: "domain",
      label: "Domain",
      requiredErrorMsg: "Domain field is required",
    },
  },
};
